name: CI

on: [push]

jobs:
  buildApplication:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [linux]
        arch: [arm]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'
#      - name: Install dependencies
#        run: |
#          go get -u golang.org/x/lint/golint
      - name: Build application
        run: GOOS=linux GOARCH=arm go build .
      - uses: actions/upload-artifact@v2
        name: Upload artifacts
        with:
          name: pokypiapp
          path: pokypiapp
